## TODO Check Doctrine Cache
framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        # prefix_seed: your_vendor_name/app_name

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:
        app: cache.adapter.redis  ## This is used for setting our cache keys
        # system: cache.adapter.redis ## TODO: check what this is used for

        default_redis_provider: 'redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%'


        ## TODO Double Check this
        # pools:
        #     my_redis_counter_cache: # A specific pool for counters, if you want
        #         adapter: cache.adapter.redis
        #         provider: 'redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%'
        #         default_lifetime: 0 # Optional: Set a default lifetime (0 for no expiration)
                
        #     doctrine.metadata_cache:
        #         adapter: cache.adapter.redis
        #         # provider: default_redis_provider
        #         # Metadata doesn't expire often, but giving it a long TTL is safe
        #         default_lifetime: 86400 # 24 hours (or even longer)

        #     doctrine.query_cache:
        #         adapter: cache.adapter.redis
        #         # provider: default_redis_provider
        #         default_lifetime: 3600 # 1 hour

        #     doctrine.result_cache:
        #         adapter: cache.adapter.redis
        #         # provider: default_redis_provider
        #         # Results typically expire faster as data changes
        #         default_lifetime: 600 # 10 minutes (adjust based on data freshness needs)