apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - php.yaml
  - worker-email.yaml
  - worker-competition-status.yaml
  - worker-submission-high-priority.yaml
  - worker-submission-low-priority.yaml
  - cronjob.yaml

images:
  - name: 127.0.0.1:32000/app-php-prod
    newTag: v1.0.29